apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert --volumes hostPath --verbose
      --out /home/akurnya/odk/komposed/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mail
  name: mail
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert --volumes hostPath
          --verbose --out /home/akurnya/odk/komposed/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: mail
    spec:
      containers:
      - env:
        - name: MAILNAME
        image: itsissa/namshi-smtp:4.89-2.deb9u5
        name: mail
        resources: {}
        volumeMounts:
        - mountPath: /etc/exim4/_docker_additional_macros
          name: mail-hostpath0
          readOnly: true
        - mountPath: /etc/exim4/domain.key
          name: mail-hostpath1
          readOnly: true
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/akurnya/odk/home/akurnya/odk/files/dkim/config
        name: mail-hostpath0
      - hostPath:
          path: /home/akurnya/odk/home/akurnya/odk/files/dkim/rsa.private
        name: mail-hostpath1
status: {}
