apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert --volumes hostPath
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mail
  name: mail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert --volumes hostPath
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: mail
    spec:
      containers:
      - env:
        - name: MAILNAME
        image: itsissa/namshi-smtp:4.89-2.deb9u5
        imagePullPolicy: ""
        name: mail
        resources: {}
        volumeMounts:
        - mountPath: /etc/exim4/_docker_additional_macros
          name: mail-hostpath0
          readOnly: true
        - mountPath: /etc/exim4/domain.key
          name: mail-hostpath1
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /Users/akul.mathur/Documents/odk/files/dkim/config
        name: mail-hostpath0
      - hostPath:
          path: /Users/akul.mathur/Documents/odk/files/dkim/rsa.private
        name: mail-hostpath1
status: {}
