apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert --volumes hostPath --verbose
      --out /home/akurnya/odk/komposed/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert --volumes hostPath
          --verbose --out /home/akurnya/odk/komposed/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DATABASE
          value: odk
        - name: POSTGRES_PASSWORD
          value: odk
        - name: POSTGRES_USER
          value: odk
        image: postgres:9.6
        name: postgres
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/akurnya/odk
        name: postgres-hostpath0
status: {}
