apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert --volumes hostPath
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: service
  name: service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert --volumes hostPath
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: service
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - postgres:5432
        - --
        - ./start-odk.sh
        env:
        - name: DOMAIN
        image: codecakes/service
        imagePullPolicy: ""
        name: service
        resources: {}
        volumeMounts:
        - mountPath: /data/target/
          name: service-hostpath0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /Users/akul.mathur/Documents/odk/data/target
        name: service-hostpath0
status: {}
